theme: jekyll-theme-cayman
This research project has been studied and completed by Martí Buxeda Sardans in the "Design & Development of Videogames" degree, realized in the Tech Talent Center CITM/UPC university. This project was supported by Ramon de Santa Maria
